#!/usr/bin/env node
/**
 * Download the web fonts from Google and write a self-hosted stylesheet.
 *
 * WHY: the two <link> tags to fonts.googleapis.com were the single most
 * expensive thing on the page. Lighthouse measured 871 ms + 184 ms of
 * render-blocking time for them on throttled mobile, out of 2,220 ms total,
 * and that is before the fonts themselves are fetched — the CSS lives on
 * fonts.googleapis.com and the woff2 files on fonts.gstatic.com, so a cold
 * visit pays DNS + TLS twice on two origins the browser cannot even start
 * looking up until it has parsed our HTML.
 *
 * Serving the same files from our own origin removes both round trips: the
 * connection is already warm, HTTP/2 multiplexes them alongside the CSS, and
 * they can be preloaded from the document head.
 *
 * It also removes a third party from every page load, which is the honest
 * position for a site that shows a GDPR consent banner — Google Fonts hands
 * the visitor's IP to Google before anyone has consented to anything.
 *
 * RUN (only when the font list changes):
 *   node scripts/fetch-fonts.mjs
 *
 * Writes:
 *   public/fonts/*.woff2      the font files
 *   public/fonts/fonts.css    @font-face rules pointing at them
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'public', 'fonts');

// A modern desktop UA, or Google serves the legacy TTF/EOT stylesheet.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

// The site is Bulgarian first, English second: Cyrillic is not optional.
// Vietnamese and Greek are dropped — nothing on the site renders them, and
// each unused subset is another file in the directory.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);

// Exactly the families and weights styles.css actually asks for.
const CSS_URL = 'https://fonts.googleapis.com/css2' +
  '?family=Italiana' +
  '&family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400' +
  '&family=Jost:wght@300;400;500;600' +
  '&display=swap';

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function run() {
  const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
  const css = await res.text();

  await fs.mkdir(OUT_DIR, { recursive: true });

  // Each @font-face is preceded by a `/* subset */` comment.
  const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face \{[^}]*\})/g)];
  if (!blocks.length) throw new Error('could not parse any @font-face blocks');

  const downloaded = new Map(); // remote url -> local filename
  const out = [];
  let kept = 0, skipped = 0, bytes = 0;

  for (const [, subset, block] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) { skipped++; continue; }

    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = (block.match(/font-weight:\s*([^;]+);/) || [])[1].trim();
    const style  = (block.match(/font-style:\s*([^;]+);/) || [])[1].trim();
    const url    = (block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+\.woff2)\)/) || [])[1];
    const range  = (block.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!family || !url) continue;

    let file = downloaded.get(url);
    if (!file) {
      file = `${slug(family)}-${style}-${weight.replace(/\s+/g, '_')}-${subset}.woff2`;
      const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
      await fs.writeFile(path.join(OUT_DIR, file), buf);
      downloaded.set(url, file);
      bytes += buf.length;
      console.log(`  ↓ ${(buf.length / 1024).toFixed(1).padStart(6)} KB  ${file}`);
    }

    kept++;
    out.push(
      `/* ${family} ${style} ${weight} — ${subset} */\n` +
      `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${file}') format('woff2');\n` +
      (range ? `  unicode-range: ${range};\n` : '') +
      `}`
    );
  }

  const header =
    `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `   Self-hosted so the page never blocks on fonts.googleapis.com.\n` +
    `   Subsets: ${[...KEEP_SUBSETS].join(', ')} (Cyrillic is required — the site is Bulgarian). */\n\n`;
  await fs.writeFile(path.join(OUT_DIR, 'fonts.css'), header + out.join('\n\n') + '\n', 'utf8');

  console.log(`\n[fonts] ${downloaded.size} files (${(bytes / 1024).toFixed(0)} KB), ` +
              `${kept} @font-face rules, ${skipped} skipped as unused subsets`);
}

run().catch(err => { console.error('[fonts] failed:', err.message); process.exit(1); });
