// Real blog posts — imported from WordPress export 2026-05-15
// NOTE: heavy `content` HTML lives in blog_content.js (lazy-loaded).

export const BLOG_POSTS = [
  {
    id: 25957256,
    slug: "bulchinska-roklia-moment-ne-prosto-pokupka",
    title: "Булчинска рокля – момент, не просто покупка",
    seo_title: "Булчинска рокля в София – Demetrios бутик Арети",
    seo_description: "Намерете булчинска рокля, която е ваша. Арети е официален представител на Demetrios за България. Луксозни колекции, консултация в София.",
    title_en: "A Wedding Dress — A Moment, Not Just a Purchase",
    seo_title_en: "Wedding Dresses in Sofia – Demetrios | Areti",
    seo_description_en: "Find a wedding dress that is truly yours. Areti is the official Demetrios representative in Bulgaria, with luxury collections and consultations in Sofia.",
    excerpt_en: "Choosing a wedding dress is rarely just a purchase — it is where anticipation, emotion and your own story meet. Discover how a modern bridal boutique in Sofia turns it into an experience.",
    category_en: "Wedding Dresses",
    date_en: "6 March 2026",
    faq_en: [],
    isoDate: "2026-03-06",
    date: "6 Март 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2025/11/Магазини-за-бални-и-абитуриентски-рокли-София-DP523_4-2.webp",
    excerpt: "Изборът на сватбена рокля рядко е просто покупка. Това е момента, в който очакването, емоцията и личната история се срещат. Затова в един модерен сватбен бутик в София предлага разнообразие от модели рокли.  Булките не т…",
    relatedRefs: ["dp523","dr407","l1508","8264"],
  },
  {
    id: 25957241,
    slug: "bulchinska-vizia-stil-siluet-useshchane",
    title: "Булчинска визия: стил, силует и усещане",
    seo_title: "Булчинска визия – стил и силует | Арети Demetrios",
    seo_description: "Открийте своята булчинска визия в Арети – официален бутик Demetrios в София. Индивидуална консултация, луксозни рокли, час за проба.",
    title_en: "Your Bridal Look: Style, Silhouette and Feeling",
    seo_title_en: "Bridal Look – Style and Silhouette | Areti Demetrios",
    seo_description_en: "Discover your bridal look at Areti — the official Demetrios boutique in Sofia. Individual consultation, luxury wedding dresses and fittings by appointment.",
    excerpt_en: "Choosing your bridal look is one of the most important moments before the wedding. At Areti Wedding Salon, brides-to-be discover refined wedding dresses that blend style, craftsmanship and femininity.",
    category_en: "Wedding Dresses",
    date_en: "2 March 2026",
    faq_en: [],
    isoDate: "2026-03-02",
    date: "2 Март 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2026/01/1520_4-scaled.webp",
    excerpt: "Изборът на булчинска визия е един от най-важните моменти в подготовката за сватбата. В Areti Wedding Salon – утвърден сватбен салон , бъдещите булки откриват изискани булчински рокли, които съчетават стил…",
    relatedRefs: ["dp523","dr407","l1536","am51"],
  },
  {
    id: 25957251,
    slug: "svatben-den-tsyalostno-prezhivyavane",
    title: "Сватбеният ден е цялостно преживяване",
    seo_title: "Сватбен магазин София – рокли и аксесоари 2026",
    seo_description: "Всичко за сватбата на едно място – булчински рокли, аксесоари и декорация. Арети бутик Demetrios в София. Запазете консултация днес.",
    title_en: "The Wedding Day Is a Complete Experience",
    seo_title_en: "Wedding Shop in Sofia – Dresses & Accessories 2026 | Areti",
    seo_description_en: "Everything for your wedding in one place — wedding dresses, accessories and decoration. Areti, the Demetrios boutique in Sofia. Book a consultation today.",
    excerpt_en: "The wedding day is not only about the dress — it is a complete experience and atmosphere. In a well-organised boutique you can find everything the day needs.",
    category_en: "Wedding Dresses",
    date_en: "27 February 2026",
    faq_en: [],
    isoDate: "2026-02-27",
    date: "27 Февруари 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2026/01/1521_4-scaled.webp",
    excerpt: "Сватбения ден не е само роклята- тя е цялостно преживяване и атмосфера. В добре оргазнизирания бутик можете да откриете:",
    relatedRefs: ["dp523","l1536","dp485","l1508"],
  },
  {
    id: 25957246,
    slug: "balna-roklia-spored-figurata",
    title: "Бална рокля според фигурата",
    seo_title: "Бална рокля според фигурата – как да изберем",
    seo_description: "Как да изберете перфектната бална рокля за вашата фигура. Вечерни и бални рокли в Арети – Sofia бутик с луксозни колекции. Вижте сега.",
    title_en: "The Right Ball Gown for Your Figure",
    seo_title_en: "Ball Gown for Your Figure – How to Choose | Areti",
    seo_description_en: "How to choose the perfect ball gown for your figure. Evening and ball gowns at Areti — a Sofia boutique with luxury collections. Take a look now.",
    excerpt_en: "Choosing an evening dress blends emotion, style and strategy. Learn how to choose a gown that suits your figure and body type, so you look balanced and feel confident.",
    category_en: "Style",
    date_en: "13 February 2026",
    faq_en: [],
    isoDate: "2026-02-13",
    date: "13 Февруари 2026",
    category: "Стил",
    image: "/wp-content/uploads/2025/11/Булчински-рокли-Demetrios-DR436-1.webp",
    excerpt: "Изборът на вечерна рокля е момент, който комбинира емоция, стил и стратегия. Всяка рокля носи различно усещане, но само една ще бъде идеалната рокля за твоята фигура и тип тяло. Когато знаеш как да избереш рокля според ф…",
    relatedRefs: ["dp523","dr407","1249","dp485"],
  },
  {
    id: 15393,
    slug: "nameri-svoyata-roklia-areti",
    title: "Намери своята рокля в Арети",
    seo_title: "Намери своята булчинска рокля в Арети – Demetrios",
    seo_description: "Булчински салон Арети е официален представител на Demetrios в България. Луксозни рокли, лично отношение и консултация в София.",
    title_en: "Find Your Dress at Areti",
    seo_title_en: "Find Your Wedding Dress at Areti | Areti Sofia",
    seo_description_en: "Areti is the official Demetrios representative in Bulgaria. Luxury wedding dresses, a personal touch and expert consultation in Sofia.",
    excerpt_en: "There comes a moment in the search for your bridal look when tiredness and confusion take over. So many styles, so many opinions, so many \"shoulds\".",
    category_en: "Wedding Dresses",
    date_en: "31 January 2026",
    faq_en: [],
    isoDate: "2026-01-31",
    date: "31 Януари 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2026/01/1502_4-scaled.webp",
    excerpt: "Има момент в търсенето на булчинска визия, в който умората и объркването взема превес. Толкова стилове, толкова мнения, толкова \"трябва\".",
    relatedRefs: ["dp523","1249","l1536","am51"],
  },
  {
    id: 14561,
    slug: "koi-e-demetrios",
    title: "Кой е Demetrios?",
    seo_title: "Кой е Demetrios? Историята на булчинската марка",
    seo_description: "Demetrios е световна марка за булчински рокли, официално представена в България от Арети. Открийте историята и колекциите в София.",
    title_en: "Who Is Demetrios?",
    seo_title_en: "Who Is Demetrios? The Bridal Brand Story | Areti",
    seo_description_en: "Demetrios is a global wedding dress brand, officially represented in Bulgaria by Areti. Discover the story and collections in Sofia.",
    excerpt_en: "Greek fashion icon Demetrios James Elias discovered his talent and passion for design while helping his parents in the family wedding dress shop in Warren, Ohio. In 1980 he realised his dream was to own his own brand.",
    category_en: "The Brand",
    date_en: "3 October 2025",
    faq_en: [],
    isoDate: "2025-10-03",
    date: "3 Октомври 2025",
    category: "Марка",
    image: "/wp-content/uploads/2025/10/demetrios-dzhejms-elias-.webp",
    excerpt: "Гръцката модна икона Demetrios Джеймс Елиас открива таланта и страстта  към дизайна, докато помага на родителите си в семейния магазин за булчински рокли  в Уорън, Охайо. През 1980 г. той осъзнава, че мечтата му е  да пр…",
    relatedRefs: ["dp523","dr407","1249","l1508"],
  },
  {
    id: 25957260,
    slug: "kak-da-izberete-bulchinska-roklia-sofia",
    title: "Как да изберете булчинска рокля — съвети от Арети след 30 години опит",
    seo_title: "Как да изберете булчинска рокля в София | Арети × Demetrios",
    seo_description: "Практически наръчник от Арети, София — официален представител на Demetrios. Силует, бюджет и проба: всичко важно, преди да изберете булчинска рокля.",
    title_en: "How to Choose a Wedding Dress — Areti's Advice from 30 Years' Experience",
    seo_title_en: "How to Choose a Wedding Dress | Areti Sofia",
    seo_description_en: "A practical guide from Areti, Sofia — the official Demetrios representative. Silhouette, budget and fittings: all you need before choosing a wedding dress.",
    excerpt_en: "When to start, which silhouette to choose, how much to budget — after more than 30 years as the official Demetrios representative in Bulgaria, we know every detail. Here are clear answers, with no marketing.",
    category_en: "Wedding Dresses",
    date_en: "29 May 2026",
    faq_en: [{"q":"How much does a Demetrios wedding dress cost?","a":"It depends on the collection. Destination Romance and Cosmobella start at €1,000. The classic Demetrios line is €1,300–2,500. Platinum reaches €4,000. All prices include free alterations."},{"q":"Do I need to book an appointment in advance?","a":"Yes — we work by appointment only, so we can give you a consultant's full attention for 90 minutes."},{"q":"How many dresses can I try at the first appointment?","a":"There is no limit. Our experience shows that 6–8 dresses give a good sense of things without becoming overwhelming."},{"q":"Can I order a dress that is not on display in the showroom?","a":"Yes. We offer access to the full Demetrios catalogues and order your chosen style directly."},{"q":"Do you alter the dress?","a":"Yes. Every dress bought from us includes free alterations — size, length, neckline details — with experienced seamstresses in the salon."}],
    isoDate: "2026-05-29",
    date: "29 Май 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2026/06/kak-da-izberete-bulchinska-roklia-demetrios-1511-areti-sofia.webp",
    excerpt: "Кога да започнете, какъв силует да изберете, колко да отделите — след повече от 30 години като официален представител на Demetrios в България, знаем всяка подробност. Ето конкретни отговори, без маркетинг.",
    relatedRefs: ["dp523","dr407","l1508","1249"],
    faq: [{"q":"Колко струва булчинска рокля от Demetrios?","a":"Зависи от колекцията. Destination Romance и Cosmobella започват от 1 000 €. Класическата Demetrios линия е 1 300–2 500 €. Platinum достига 4 000 €. Всички цени включват безплатни корекции."},{"q":"Трябва ли да запазвам час предварително?","a":"Да — работим само с предварителни записвания, за да можем да ви посветим пълното внимание на консултант за 90 минути."},{"q":"Колко рокли мога да пробвам на първата среща?","a":"Няма ограничение. Нашата практика показва, че 6–8 рокли дават добра представа без претоварване."},{"q":"Мога ли да поръчам рокля, която не е изложена в шоурума?","a":"Да. Предлагаме достъп до пълните каталози на Demetrios и поръчваме избрания от вас модел директно."},{"q":"Правите ли корекции на роклята?","a":"Да. Всяка купена при нас рокля включва безплатни корекции — размер, дължина, детайли по деколтето — с опитни шивачи в салона."}],
  },
  {
    id: 30010001,
    slug: "bulchinski-rokli-tseni-2026",
    title: "Булчински рокли цени 2026/2027 — пълен наръчник за бюджета",
    seo_title: "Булчински рокли цени 2026/2027 — от 1 000 € | Арети София",
    seo_description: "Колко струва булчинска рокля в България през 2026 и 2027? Ценови диапазони по колекциите Demetrios, Cosmobella и Platinum.",
    title_en: "Wedding Dress Prices in Sofia, Bulgaria — 2026/2027 Guide",
    seo_title_en: "Wedding Dress Prices Sofia 2026/2027 — from €1,000 | Areti",
    seo_description_en: "How much does a wedding dress cost in Sofia? Real price ranges by collection — Cosmobella, Demetrios, Platinum — and what is included.",
    excerpt_en: "How much does a wedding dress cost in Sofia? A practical guide to prices by collection, what is included, seasonal sales and when to order.",
    category_en: "Wedding Dresses",
    date_en: "10 June 2026",
    faq_en: [{"q":"How much does a wedding dress cost at Areti in Sofia?","a":"Prices range from €1,000 (Cosmobella) to €4,000 (Demetrios Platinum). Every price includes a stylist consultation, unlimited try-ons and one free alteration."},{"q":"Are there wedding dress sales in Sofia?","a":"Yes — Areti periodically discounts previous-season styles by up to 30%. Ask about current offers when booking your fitting."},{"q":"What is included in the price?","a":"A personal stylist consultation, unlimited try-ons, one free alteration fitted to your figure and a guarantee that every gown is an original Demetrios."},{"q":"Can I order a dress that is not in the showroom?","a":"Yes. As the official Demetrios representative for Bulgaria, Areti can order any current-season style. Delivery takes 3–4 months, plus 1–2 months for alterations."}],
    isoDate: "2026-06-10",
    date: "10 Юни 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2025/10/булчински-рокли-София1500_1-scaled.webp",
    excerpt: "Колко струва булчинска рокля в София през 2026 и 2027? Подробен наръчник с цени по колекции, какво влияе на цената и как да планирате бюджета за сватбена рокля.",
    relatedRefs: ["1500","1501","dp523","1249","dr407","1505"],
    faq: [{"q":"Колко струва булчинска рокля в Арети?","a":"Цените варират от 1 000 € (Cosmobella) до 4 000 € (Demetrios Platinum). В цената е включена консултация и една безплатна корекция."},{"q":"Има ли намаления на булчински рокли?","a":"Да, периодично предлагаме намаления на модели от предишни сезони — до 30%. Питайте за актуалните промоции при запазване на час."},{"q":"Какво е включено в цената на булчинската рокля?","a":"Консултация с личен стилист, неограничен брой проби, една безплатна корекция и гаранция за оригиналност."},{"q":"Защо булчинските рокли Demetrios са по-скъпи?","a":"Demetrios използва висококачествени материи, ръчна бродерия и детайли. Всяка рокля минава през строг контрол на качеството. Цената отразява международните стандарти на марката."}],
  },
  {
    id: 30010002,
    slug: "svatbeni-rokli-kak-da-namerite-perfektnata",
    title: "Сватбени рокли — как да намерите перфектната за вас",
    seo_title: "Сватбени рокли — как да изберете перфектната | Арети София",
    seo_description: "Пълен наръчник за избор на сватбена рокля — от определяне на стила и силуета до пробата в салона. Практични съвети от стилистите на Арети.",
    title_en: "Wedding Dresses — How to Find the Perfect One for You",
    seo_title_en: "Wedding Dresses — How to Choose | Areti Sofia",
    seo_description_en: "A complete guide to choosing a wedding dress in Sofia — from style and silhouette to the salon fitting. Practical advice from Areti's stylists.",
    excerpt_en: "How do you choose the perfect wedding dress? A step-by-step guide — from defining your style to the final fitting. Advice from Areti's stylists.",
    category_en: "Wedding Dresses",
    date_en: "10 June 2026",
    faq_en: [{"q":"When is the best time to look for a wedding dress?","a":"8–12 months before the wedding. For urgent cases we have dresses in stock that we can alter in 2–3 weeks."},{"q":"How many times do I need to visit the salon?","a":"Most brides find their dress in 2–3 visits. The first appointment is for orientation, the second for finalising the choice."},{"q":"Can I try dresses from different collections?","a":"Yes. With us you can combine fittings from Demetrios, Cosmobella, Platinum and Destination Romance in a single visit."},{"q":"What should I do if I don't find my dress?","a":"Book a second appointment — the stylist will select different styles. We also have access to the full Demetrios catalogue for special orders."}],
    isoDate: "2026-06-10",
    date: "10 Юни 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2025/11/Магазини-за-бални-и-абитуриентски-рокли-София-DP523_4-2.webp",
    excerpt: "Как да изберете перфектната сватбена рокля? Наръчник стъпка по стъпка — от определяне на стила до финалната проба. Съвети от стилистите на Арети.",
    relatedRefs: ["dp523","1501","dr407","1505","1500","dp485"],
    faq: [{"q":"Кога е най-доброто време за търсене на сватбена рокля?","a":"8–12 месеца преди сватбата. За спешни случаи разполагаме с рокли в наличност, които можем да коригираме за 2–3 седмици."},{"q":"Колко пъти трябва да посетя салона?","a":"Повечето булки намират роклята си на 2–3 визити. Първата среща е за ориентация, втората — за финализиране на избора."},{"q":"Мога ли да пробвам рокли от различни колекции?","a":"Да. При нас можете да комбинирате проби от Demetrios, Cosmobella, Platinum и Destination Romance на едно посещение."},{"q":"Какво да правя, ако не намеря роклята си?","a":"Запишете втори час — стилистът ще подбере различни модели. Имаме достъп и до пълния каталог на Demetrios за специални поръчки."}],
  },
  {
    id: 30010003,
    slug: "bulchinska-roklia-silueti-narachnik",
    title: "Силуети булчински рокли — кой е подходящ за вас?",
    seo_title: "Силуети булчински рокли — А-силует, русалка, принцеса | Арети",
    seo_description: "Подробен наръчник за 5-те основни силуета булчински рокли — А-силует, русалка, принцеса, права линия и бохо. Кой е подходящ за вашата фигура?",
    title_en: "Wedding Dress Silhouettes — Which One Is Right for You?",
    seo_title_en: "Wedding Dress Silhouettes Guide | Areti Sofia",
    seo_description_en: "A complete guide to the 5 main wedding dress silhouettes — A-line, mermaid, ball gown, column and boho. Which suits your figure? Book a fitting in Sofia.",
    excerpt_en: "Which wedding dress silhouette suits your figure? A complete guide to the A-line, mermaid, ball gown, column and boho — with examples from the Demetrios collections.",
    category_en: "Wedding Dresses",
    date_en: "10 June 2026",
    faq_en: [{"q":"Which silhouette is best for my figure?","a":"The A-line is versatile and flatters every body type. The mermaid is for curves, the ball gown skims the hips, and the column suits tall, slender brides. We recommend trying on different silhouettes."},{"q":"Which silhouette is the most comfortable for a full day?","a":"The A-line and boho styles are the most comfortable — they're light and never restrict movement. The ball gown and mermaid are heavier and more restrictive."},{"q":"Can I combine elements from different silhouettes?","a":"To a degree, yes. Many dresses, for example, pair a fitted bodice (mermaid) with an A-line skirt. At Areti we'll show you hybrid styles."}],
    isoDate: "2026-06-10",
    date: "10 Юни 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2025/10/bride-to-be1505_1--scaled.webp",
    excerpt: "Кой силует булчинска рокля е подходящ за вашата фигура? Подробен наръчник за А-силует, русалка, принцеса, права линия и бохо — с примери от колекциите на Demetrios.",
    relatedRefs: ["1500","1501","dp523","1505","dr407","dp485"],
    faq: [{"q":"Кой силует е най-подходящ за моята фигура?","a":"А-силуетът е универсален и подходящ за всеки тип фигура. Русалката е за извивки, принцесата скрива бедрата, правата линия е за високи и стройни. Препоръчваме проба на различни силуети."},{"q":"Кой силует е най-удобен за цял ден?","a":"А-силуетът и бохо стилът са най-удобни — не ограничават движението и са леки. Принцесата и русалката са по-тежки и ограничаващи."},{"q":"Мога ли да комбинирам елементи от различни силуети?","a":"В известна степен — да. Например, много рокли съчетават прилепнал горен дял (русалка) с А-силует пола. В Арети ще ви покажем хибридни модели."}],
  },
  {
    id: 30010004,
    slug: "luksozni-bulchinski-rokli",
    title: "Луксозни булчински рокли — когато детайлът е всичко",
    seo_title: "Луксозни булчински рокли Demetrios Platinum | Арети София",
    seo_description: "Открийте луксозните булчински рокли Demetrios Platinum — ръчна бродерия, кристали, перли и ексклузивни дантели. Цени от 2 500 €. Час за проба в Арети.",
    title_en: "Luxury Wedding Dresses — When the Detail Is Everything",
    seo_title_en: "Luxury Demetrios Platinum Dresses | Areti Sofia",
    seo_description_en: "Discover the luxury Demetrios Platinum wedding dresses in Sofia — hand embroidery, crystals, pearls and exclusive laces. From €2,500. Book a fitting at Areti.",
    excerpt_en: "The luxury Demetrios Platinum wedding dresses — for brides who want something truly special. Hand embroidery, crystals, pearls and exclusive laces.",
    category_en: "Wedding Dresses",
    date_en: "10 June 2026",
    faq_en: [{"q":"What makes a luxury wedding dress different?","a":"Handcraftsmanship (200+ hours), high-quality European fabrics, an exclusive design with crystals and pearls, a perfect cut and limited availability."},{"q":"How much do the luxury Demetrios Platinum dresses cost?","a":"Prices range from €2,500 to €4,000. The price includes a consultation, a fitting and one alteration."},{"q":"Is a luxury dress worth the investment?","a":"It depends on your priorities. If you have an eye for detail and want a dress for a large, formal wedding — yes. The difference shows in the photographs and in how it feels."}],
    isoDate: "2026-06-10",
    date: "10 Юни 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2025/11/Сватбен-салон-София-DP523_1-2.webp",
    excerpt: "Луксозните булчински рокли Demetrios Platinum — за булки, които искат нещо наистина специално. Ръчна бродерия, кристали, перли и ексклузивни дантели.",
    relatedRefs: ["dp523","dp485","dp527","dp529","dp548","dp480"],
    faq: [{"q":"Какво прави луксозната булчинска рокля различна?","a":"Ръчна изработка (200+ часа), висококачествени европейски материи, ексклузивен дизайн с кристали и перли, перфектна кройка и ограничена наличност."},{"q":"Колко струват луксозните рокли Demetrios Platinum?","a":"Цените варират от 2 500 до 4 000 €. В цената е включена консултация, проба и една корекция."},{"q":"Заслужава ли си инвестицията в луксозна рокля?","a":"Зависи от приоритетите ви. Ако ценителите на детайли и искате рокля за голяма, представителна сватба — да. Разликата се вижда на снимките и в усещането."}],
  },
  {
    id: 30010005,
    slug: "bulchinski-rokli-sofia-svatben-salon",
    title: "Булчински рокли в София — защо Арети е салонът, който булките избират от 1992 г.",
    seo_title: "Булчински рокли София — сватбен салон Арети | Demetrios от 1992 г.",
    seo_description: "Търсите булчински рокли в София? Арети е официален представител на Demetrios от 1992 г. Над 100 рокли, консултация и корекции в Лозенец. Запазете час.",
    title_en: "Wedding Dresses in Sofia — Why Areti Is the Salon Brides Have Chosen Since 1992",
    seo_title_en: "Wedding Dresses Sofia — Areti Bridal Salon",
    seo_description_en: "Looking for wedding dresses in Sofia? Areti is the official Demetrios representative since 1992. Over 100 dresses, consultation and alterations in Lozenets.",
    excerpt_en: "Wedding dresses in Sofia — why Areti is the bridal salon brides have chosen for more than 30 years. Demetrios, fittings, alterations and personal service.",
    category_en: "Wedding Dresses",
    date_en: "10 June 2026",
    faq_en: [{"q":"Where is Areti salon located?","a":"At 63 Krum Popov Street, Lozenets, Sofia — close to Yuzhen Park. There is free parking."},{"q":"Do I need to book a fitting?","a":"Yes. We work by appointment only, so we can give every bride our personal attention. Book online or on +359 878 521 660."},{"q":"Is Areti an official Demetrios representative?","a":"Yes — the only one in Bulgaria since 1992. All the dresses are originals, with an international quality guarantee."},{"q":"What is included in the price of the dress?","a":"A consultation, unlimited fittings, one free alteration and a guarantee of authenticity."},{"q":"How many dresses do you have in the salon?","a":"Over 100 styles from 4 collections — Cosmobella, Demetrios, Destination Romance and Platinum. Plus access to the full catalogue for special orders."}],
    isoDate: "2026-06-10",
    date: "10 Юни 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2025/11/Магазини-за-булчински-рокли-София-DP523_2-2.webp",
    excerpt: "Булчински рокли в София — защо Арети е сватбеният салон, който булките избират повече от 30 години. Demetrios, час за проба, корекции и лично обслужване.",
    relatedRefs: ["dp523","1500","1501","dr407","1505","1249"],
    faq: [{"q":"Къде се намира салон Арети?","a":"На ул. Крум Попов 63, кв. Лозенец, София — близо до Южен парк. Има безплатен паркинг."},{"q":"Трябва ли да запазя час за проба?","a":"Да. Работим само с предварителни часове, за да осигурим персонално внимание за всяка булка. Запазете онлайн или на +359 878 521 660."},{"q":"Арети е ли официален представител на Demetrios?","a":"Да — единственият в България от 1992 г. Всички рокли са оригинални, с международна гаранция за качество."},{"q":"Какво е включено в цената на роклята?","a":"Консултация, неограничен брой проби, една безплатна корекция и гаранция за оригиналност."},{"q":"Колко рокли имате в салона?","a":"Над 100 модела от 4 колекции — Cosmobella, Demetrios, Destination Romance и Platinum. Плюс достъп до пълния каталог за специални поръчки."}],
  },
  {
    id: 30010006,
    slug: "abiturientski-balni-rokli-sofia",
    title: "Абитуриентски и бални рокли в София — как да изберете своята",
    seo_title: "Абитуриентски и бални рокли София 2027 | Арети",
    seo_description: "Търсите абитуриентска или бална рокля в София? Елегантни вечерни рокли за бал, сватба и специални поводи — съвети за избор по фигура и цени.",
    title_en: "Prom and Evening Dresses in Sofia — How to Choose Yours",
    seo_title_en: "Prom & Evening Dresses in Sofia 2027 | Areti",
    seo_description_en: "Looking for a prom or evening dress in Sofia? How to choose by silhouette, colour and fabric, when to book and how alterations work — from Areti.",
    excerpt_en: "Prom is the first big occasion you dress for on your own terms. How to choose the right prom or evening dress — silhouette, colour, fabric and timing — from Areti's stylists in Sofia.",
    category_en: "Evening Dresses",
    date_en: "2 July 2026",
    faq_en: [{"q":"When should I start looking for a prom dress?","a":"4–6 months before the ball — from December to February. For last-minute cases we keep styles in stock that we can alter within days."},{"q":"Which evening dress silhouettes do you offer?","a":"A-line (the most versatile), mermaid and ball gown — in a range of colours and fabrics from Areti's evening collection."},{"q":"Do you alter evening dresses?","a":"Yes, on site in the salon — length, taking in, straps and neckline. It takes from a few days to two weeks."},{"q":"Can I wear the evening dress for another occasion?","a":"Of course — our clients wear the evening styles to weddings, christenings, cocktails and corporate events."}],
    isoDate: "2026-07-02",
    date: "2 Юли 2026",
    category: "Вечерни рокли",
    image: "/wp-content/uploads/2025/11/Булчински-рокли-Demetrios-DR436-1.webp",
    excerpt: "Абитуриентският бал е първото голямо официално събитие в живота на всяка девойка. Как да изберете перфектната абитуриентска или бална рокля — съвети за силует, цвят и материя от стилистите на Арети в София.",
    relatedRefs: ["dr436","dr437","d291","r141","r157","r177"],
    faq: [{"q":"Кога да започна да търся абитуриентска рокля?","a":"4–6 месеца преди бала — от декември до февруари. За спешни случаи имаме модели в наличност, които коригираме за дни."},{"q":"Какви силуети бални рокли предлагате?","a":"А-силует (най-универсален), русалка и принцеса — в различни цветове и материи от вечерната колекция на Арети."},{"q":"Правите ли корекции на балните рокли?","a":"Да, на място в салона — дължина, стесняване, презрамки и деколте. Отнема от няколко дни до две седмици."},{"q":"Мога ли да нося балната рокля и на друг повод?","a":"Разбира се — нашите клиентки носят вечерните модели на сватби, кръщенета, коктейли и фирмени събития."}],
  },
  {
    id: 30010007,
    slug: "svatbeni-rokli-sofia",
    title: "Сватбени рокли в София — пълен наръчник (2026/2027)",
    seo_title: "Сватбени рокли София 2026/2027 — 100+ модела | Арети",
    seo_description: "Сватбени рокли в София — над 100 модела Demetrios в салон Арети от 1992 г. Цени от 1 000 до 4 000 €. Силуети, цени и как да изберете. Час за проба.",
    title_en: "Wedding Dresses in Sofia, Bulgaria — The Complete Guide (2026/2027)",
    seo_title_en: "Wedding Dresses Sofia, Bulgaria — 100+ Gowns | Areti",
    seo_description_en: "Looking for a wedding dress in Sofia? Where to shop, silhouettes, prices from €1,000, fittings and alterations — a complete guide from Areti.",
    excerpt_en: "Looking for a wedding dress in Sofia? A complete guide to silhouettes, prices and fittings — from Areti, the official Demetrios salon since 1992.",
    category_en: "Wedding Dresses",
    date_en: "20 July 2026",
    faq_en: [{"q":"Where can I buy a wedding dress in Sofia?","a":"Areti, at 63 Krum Popov St in the Lozenets district, has been the official Demetrios representative for Bulgaria since 1992, with over 100 gowns in the salon and prices from €1,000 to €4,000."},{"q":"How much do wedding dresses cost in Sofia?","a":"At Areti prices run from €1,000 (Cosmobella) to €4,000 (Demetrios Platinum), including a stylist consultation, unlimited try-ons and one free alteration."},{"q":"When should I start looking for my dress?","a":"Ideally 8–12 months before the wedding. A Demetrios order takes 3–4 months plus 1–2 months for alterations; in-stock styles can be ready in 2–3 weeks."},{"q":"Can international brides book a fitting?","a":"Yes — brides travel to Areti from abroad for their gowns. Fittings are by appointment; book online and we will arrange everything around your visit to Sofia."},{"q":"Are the dresses original?","a":"Yes. Areti is the official Demetrios representative for Bulgaria — every gown is 100% original with an international quality guarantee."}],
    isoDate: "2026-07-20",
    date: "20 Юли 2026",
    category: "Сватбени рокли",
    image: "/wp-content/uploads/2025/10/сватбени-рокли1500_2-scaled.webp",
    excerpt: "Търсите сватбени рокли в София? Наръчник за силуети, цени и как да изберете перфектната рокля — от салон Арети, официален представител на Demetrios от 1992 г.",
    relatedRefs: ["1500","1249","dp523","dr407","1505","1220"],
    faq: [{"q":"Къде да купя сватбена рокля в София?","a":"Салон Арети на ул. Крум Попов 63, кв. Лозенец, е официален представител на Demetrios в България от 1992 г. с над 100 сватбени рокли в наличност и цени от 1 000 до 4 000 €."},{"q":"Колко струват сватбените рокли в София?","a":"В Арети цените са от 1 000 € (Cosmobella) до 4 000 € (Demetrios Platinum). В цената влизат консултация с личен стилист, неограничен брой проби и една безплатна корекция."},{"q":"Кога да започна да търся сватбена рокля?","a":"8–12 месеца преди сватбата. Поръчка от Demetrios отнема 3–4 месеца плюс 1–2 месеца за корекции. Има и модели в наличност, готови за 2–3 седмици."},{"q":"Каква е разликата между сватбена и булчинска рокля?","a":"Няма разлика — „сватбена рокля“ и „булчинска рокля“ са синоними за роклята на булката. В Арети ги използваме взаимозаменяемо."},{"q":"Оригинални ли са роклите?","a":"Да. Арети е единственият официален представител на Demetrios в България от 1992 г. Всяка рокля е 100% оригинална, с международна гаранция за качество."}],
  },
  {
    id: 30010008,
    slug: "bulchinski-rokli-pod-naem-sofia",
    title: "Булчинска рокля под наем или покупка — какво си струва в София?",
    seo_title: "Булчински рокли под наем София — или покупка? | Арети",
    seo_description: "Наем или покупка на булчинска рокля в София? Реалната сметка: цени на наема, скритите ограничения и кога достъпната покупка от 1 000 € излиза по-изгодно.",
    title_en: "Renting or Buying a Wedding Dress — What's Worth It in Sofia?",
    seo_title_en: "Wedding Dresses to Rent in Sofia — or Buy? | Areti",
    seo_description_en: "Rent or buy a wedding dress in Sofia? The real maths: rental prices, hidden limitations, and when an affordable €1,000 purchase works out better.",
    excerpt_en: "Renting looks cheaper — but is it? An honest breakdown of what it costs to rent a wedding dress in Sofia, the limitations involved, and when a purchase from €1,000 is the wiser choice.",
    category_en: "Wedding Dresses",
    date_en: "16 August 2026",
    faq_en: [{"q":"How much does it cost to rent a wedding dress in Sofia?","a":"Most often between €150 and €400, depending on the salon and the style, usually with a deposit and a short return window. Alterations to your figure are heavily limited — the dress has to be returned in its original condition."},{"q":"Does Areti rent out wedding dresses?","a":"No — Areti sells original Demetrios wedding dresses. For brides on a tighter budget we offer the Cosmobella collection from €1,000 and periodic discounts of up to 30% on styles from previous seasons, which often work out comparable to a rental."},{"q":"Which is better value — renting or buying?","a":"It depends on the wedding. For a short civil ceremony a rental may be enough. For a full wedding with a church or outdoor ceremony, photographs and a whole day of wear, buying an affordable original dress altered to your figure usually gives you more for your money."},{"q":"What does the price include when you buy at Areti?","a":"A consultation with a personal stylist, unlimited fittings, one free alteration to your figure and a guarantee of authenticity. The dress stays yours — as a keepsake."}],
    isoDate: "2026-08-16",
    date: "16 Август 2026",
    category: "Булчински рокли",
    image: "/wp-content/uploads/2025/11/Воали-за-булки-8251_1.webp",
    excerpt: "Наемът изглежда по-евтин — но дали е? Честна сметка: какво струва наемът на булчинска рокля в София, какви са ограниченията и кога покупката от 1 000 € е по-разумният избор.",
    relatedRefs: ["8251","8257","8264","L1152","8271","8276"],
    faq: [{"q":"Колко струва наемът на булчинска рокля в София?","a":"Най-често между 150 и 400 € според салона и модела, обикновено с депозит и кратък срок за връщане. Корекциите по фигурата са силно ограничени — роклята трябва да се върне в изходния си вид."},{"q":"Дава ли Арети булчински рокли под наем?","a":"Не — Арети продава оригинални булчински рокли Demetrios. За булки с по-ограничен бюджет предлагаме колекцията Cosmobella от 1 000 € и периодични намаления до 30% на модели от предишни сезони, които често излизат сравнимо с наем."},{"q":"Кое е по-изгодно — наем или покупка?","a":"Зависи от сватбата. За кратък граждански ритуал наемът може да е достатъчен. За същинска сватба с църковна или изнесена церемония, снимки и цял ден носене, покупката на достъпна оригинална рокля с корекции по вашата фигура обикновено дава повече за парите."},{"q":"Какво включва цената при покупка от Арети?","a":"Консултация с личен стилист, неограничен брой проби, една безплатна корекция по вашата фигура и гаранция за оригиналност. Роклята остава ваша — като спомен."}],
  },
];
